

#include "Picta.h"
#include "Pictb.h"
#include "zPict.h"
#include "baCK.h"

unsigned char *GFX2=(unsigned char*)GFX21;
unsigned char *Buffer1=(unsigned char*)Buffer11;
unsigned char *Buffer2=(unsigned char*)Buffer21;
unsigned char *Picture2=(unsigned char*)Picture21;

unsigned char *Palette=(unsigned char*)Palette1;
unsigned char *PictureAPal=(unsigned char*)PictureAPal1;
unsigned char *PictureBPal=(unsigned char*)PictureBPal1;
