void ADC();
void AND65816();
void ASL();
void ASLC();
void BCC();
void BCS();
void BEQ();
void BIT();
void BMI();
void BNE();
void BPL();
void BRA();
void BRK();
void BRL();
void BVC();
void BVS();
void CLC();
void CLD();
void CLI();
void CLV();
void CMP();
void CPX();
void CPY();
void DEC();
void DECC();
void DEX();
void DEY();
void EOR();
void INC();
void INCC();
void INX();
void INY();
void JML();
void JMP();
void JSL();
void JSR();
void LDA();
void LDX();
void LDY();
void LSR();
void LSRC();
void MVN();
void MVP();
void NOP();
void ORA();
void PEA();
void PEI();
void PER();
void PHA();
void PHB();
void PHD();
void PHK();
void PHP();
void PHX();
void PHY();
void PLA();
void PLB();
void PLD();
void PLP();
void PLX();
void PLY();
void REP();
void ROL();
void ROLC();
void ROR();
void RORC();
void RTI();
void RTL();
void RTS();
void SBC();
void SEC();
void SED();
void SEI();
void SEP();
void STA();
void STP();
void STX();
void STY();
void STZ();
void TAX();
void TAY();
void TCD();
void TDC();
void TCS();
void TRB();
void TSB();
void TSC();
void TSX();
void TXA();
void TXS();
void TXY();
void TYA();
void TYX();
void WAI();
void XBA();
void XCE();






 

 

 

 
 	


		 
	
	

	
		
	



