/*
 Helper.h
*/

extern unsigned char *SNES_Screen;     // Memory for snes output

extern unsigned short BG1HScrollData;   // Storage for h scroll value
extern unsigned short BG1VScrollData;   // Storage for h scroll value
extern unsigned short BG2HScrollData;   // Storage for h scroll value
extern unsigned short BG2VScrollData;   // Storage for h scroll value
extern unsigned short BG3HScrollData;   // Storage for h scroll value
extern unsigned short BG3VScrollData;   // Storage for h scroll value
extern unsigned short BG4HScrollData;   // Storage for h scroll value
extern unsigned short BG4VScrollData;   // Storage for h scroll value

extern unsigned char *BKG1;            // I`ll merge the backgrounds to create the screen ^
extern unsigned char *BKG2;
extern unsigned char *BKG3;
extern unsigned char *BKG4;

extern unsigned long BKGA1;
extern unsigned long BKGA2;
extern unsigned long BKGA3;
extern unsigned long BKGA4;

